name: Build S2MP-Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Create lib directory
      run: |
        mkdir -p lib/Release
        mkdir -p S2MP-Mod/lib
      shell: bash
        
    - name: Download and Setup MinHook
      run: |
        # Clone MinHook repo if it doesn't exist
        if [ ! -d "minhook" ]; then
          git clone https://github.com/TsudaKageyu/minhook.git
        else
          echo "MinHook repository already exists, skipping clone"
        fi
        
        cd minhook
        # Remove existing build directory if it exists and create a new one
        if [ -d "build" ]; then
          rm -rf build
        fi
        mkdir build
        cd build
        
        cmake -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=OFF ..
        cmake --build . --config Release
        
        # Create the destination directories and copy to multiple locations
        mkdir -p ../../../lib/Release
        mkdir -p ../../../S2MP-Mod/lib
        mkdir -p ../../../x64/Release
        
        # Show contents for debugging
        echo "Contents of ./Release directory:"
        ls -la ./Release
        
        # Copy the library with various names to various locations
        cp ./Release/MinHook.x64.lib ../../../lib/Release/libMinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../lib/Release/MinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../libMinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../MinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../S2MP-Mod/lib/libMinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../S2MP-Mod/lib/MinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../x64/Release/libMinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../x64/Release/MinHook.x64.lib
        
        # Debug - show the copied files
        echo "Contents of lib/Release directory after copy:"
        ls -la ../../../lib/Release
        echo "Contents of S2MP-Mod/lib directory after copy:"
        ls -la ../../../S2MP-Mod/lib
        echo "Contents of x64/Release directory after copy:"
        ls -la ../../../x64/Release
        echo "Contents of root directory:"
        ls -la ../../../
        
        cd ../../
        # Ensure includes directory exists
        mkdir -p include
        cp -r minhook/include/* include/
      shell: bash
      
    - name: Modify project file to use static library reference
      run: |
        # Create a project-specific lib directory for MinHook
        if [ ! -d "S2MP-Mod/lib" ]; then
          mkdir -p S2MP-Mod/lib
        fi
        
        # Create vcxproj.user file with custom library paths
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
        <Project ToolsVersion=\"Current\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
          <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">
            <LibraryPath>$(ProjectDir)lib;$(SolutionDir)lib\Release;$(SolutionDir)x64\Release;$(SolutionDir);$(LibraryPath)</LibraryPath>
          </PropertyGroup>
        </Project>" > S2MP-Mod/S2MP-Mod.vcxproj.user
        
        # Create a simple props file to include the library
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
        <Project ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
          <ItemDefinitionGroup>
            <Link>
              <AdditionalDependencies>libMinHook.x64.lib;%(AdditionalDependencies)</AdditionalDependencies>
            </Link>
          </ItemDefinitionGroup>
        </Project>" > S2MP-Mod/MinHook.props
        
        # Create a directory.props file to define additional directories
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
        <Project ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
          <PropertyGroup>
            <LibraryPath>$(ProjectDir)lib;$(SolutionDir)lib\Release;$(SolutionDir)x64\Release;$(SolutionDir);$(LibraryPath)</LibraryPath>
          </PropertyGroup>
        </Project>" > Directory.Build.props
      shell: bash
      
    - name: Update Project Library Settings
      run: |
        REM Display current directory structure for debugging
        dir /s /b lib
        echo ---------------------
        dir /s /b x64
        echo ---------------------
        dir /s /b S2MP-Mod\lib
      shell: cmd
      
    - name: Build solution
      run: |
        REM Add additional library paths to MSBuild command
        msbuild /m /p:Configuration=Release /p:Platform=x64 /p:AdditionalLibraryDirectories="%CD%\lib\Release;%CD%;%CD%\x64\Release;%CD%\S2MP-Mod\lib" S2MP-Mod.sln
      shell: cmd
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: S2MP-Mod-Release
        path: |
          x64/Release/S2MP-Mod.dll
          x64/Release/S2MP-Mod.pdb