name: Build S2MP-Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg
        bootstrap-vcpkg.bat
      shell: cmd

    - name: Compile MinHook in Release mode
      run: |
        cd vcpkg
        git clone https://github.com/TsudaKageyu/minhook.git
        cd minhook
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release
        mkdir -p ../../installed/x64-windows-static/lib
        copy Release\MinHook.lib ../../installed/x64-windows-static/lib\libMinHook.x64.lib
      shell: cmd

    - name: Debug library files
      run: dir /s /b vcpkg\installed\x64-windows-static\lib
      shell: cmd

    - name: Copy the libMinHook.x64.lib
      run: |
        mkdir -p build_output
        mkdir -p lib/Release
        copy vcpkg\installed\x64-windows-static\lib\libMinHook.x64.lib lib/Release/libMinHook.x64.lib
      shell: cmd

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Build solution
      run: |
        msbuild S2MP-Mod.sln /p:Configuration=Release /p:Platform=x64 /p:AdditionalLibraryDirectories="%CD%\lib\Release"
      shell: cmd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: S2MP-Mod-Release
        path: build_output