name: Build S2MP-Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Create lib directory
      run: |
        mkdir -p lib/Release
        
    - name: Download and Setup MinHook
      run: |
        # Clone MinHook repo if it doesn't exist
        if [ ! -d "minhook" ]; then
          git clone https://github.com/TsudaKageyu/minhook.git
        else
          echo "MinHook repository already exists, skipping clone"
        fi
        
        cd minhook
        # Remove existing build directory if it exists and create a new one
        if [ -d "build" ]; then
          rm -rf build
        fi
        mkdir build
        cd build
        
        cmake -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=OFF ..
        cmake --build . --config Release
        
        # Create the destination directories
        mkdir -p ../../../lib/Release
        
        # Copy and rename the library file - show debug info
        echo "Contents of ./Release directory:"
        ls -la ./Release
        
        # Copy the library to the expected location
        cp ./Release/MinHook.x64.lib ../../../lib/Release/libMinHook.x64.lib
        
        # Debug - show the copied file
        echo "Contents of lib/Release directory after copy:"
        ls -la ../../../lib/Release
        
        # Also copy to the root project directory and to x64/Release as a fallback
        mkdir -p ../../../x64/Release
        cp ./Release/MinHook.x64.lib ../../../libMinHook.x64.lib
        cp ./Release/MinHook.x64.lib ../../../x64/Release/libMinHook.x64.lib
        
        cd ../../
        # Ensure includes directory exists
        mkdir -p include
        cp -r minhook/include/* include/
      shell: bash
      
    - name: Update Project Library Settings
      run: |
        # Display current directory structure for debugging
        dir /s /b lib
        dir /s /b x64
      shell: cmd
      
    - name: Build solution
      run: |
        # Add additional library path to MSBuild command
        msbuild /m /p:Configuration=Release /p:Platform=x64 /p:AdditionalLibraryDirectories="%CD%\lib\Release;%CD%" S2MP-Mod.sln
      shell: cmd
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: S2MP-Mod-Release
        path: |
          x64/Release/S2MP-Mod.dll
          x64/Release/S2MP-Mod.pdb